from spy_market_agent.research.artifacts import ResearchArtifactStore
from spy_market_agent.research.backtest_evidence import (
    BACKTEST_EVIDENCE_SCHEMA_VERSION,
    CanonicalBacktestEvidence,
    backtest_metrics_to_axiom_result,
    canonical_backtest_evidence,
)
from spy_market_agent.research.baselines import classification_baseline_probabilities
from spy_market_agent.research.calibration import build_calibration_split
from spy_market_agent.research.campaign import (
    ResearchCampaignConfig,
    campaign_config_identity,
    load_research_campaign_config,
)
from spy_market_agent.research.candidates import (
    development_hyperparameter_searches,
    development_model_registry,
)
from spy_market_agent.research.constants import (
    BOUNDARY_EXCLUSION_SESSIONS,
    DEFAULT_ASSESSMENT_WINDOW_ROWS,
    DEFAULT_STEP_ROWS,
    ENTRY_OFFSET_SESSIONS,
    EXIT_OFFSET_SESSIONS,
    FEATURE_WARMUP_ROWS,
    MANDATORY_GAP_SESSIONS,
    MINIMUM_FINAL_ASSESSMENT_ROWS,
    MINIMUM_INITIAL_TRAINING_ROWS,
    PHASE3_ARTIFACT_SCHEMA_VERSION,
    PHASE3_PHASE_ID,
    WALK_FORWARD_FOLD_POLICY_ID,
)
from spy_market_agent.research.experiment_core import (
    AXIOM_EXPERIMENT_ID_VERSION,
    AXIOM_EXPERIMENT_SCHEMA_VERSION,
    AXIOM_RESULT_ID_VERSION,
    AXIOM_RESULT_SCHEMA_VERSION,
    ExperimentDefinition,
    ExperimentLifecycleState,
    ExperimentOutcome,
    ExperimentResult,
    ResearchDatasetRef,
    ResearchEvidenceRef,
    ResearchRuntimeLineage,
    StoredExperiment,
    StoredExperimentResult,
    StrategyResearchState,
)
from spy_market_agent.research.experiment_core import (
    experiment_identity as axiom_experiment_identity,
)
from spy_market_agent.research.experiment_core import (
    result_identity as axiom_result_identity,
)
from spy_market_agent.research.folds import construct_walk_forward_manifest
from spy_market_agent.research.hyperparameters import (
    planned_trials_from_grid,
    validate_inner_training_search,
)
from spy_market_agent.research.identity import experiment_identity, fold_manifest_identity
from spy_market_agent.research.leakage import (
    FeatureGenerationPolicy,
    TransformationFitRecord,
    validate_no_forbidden_feature_columns,
    validate_phase2_final_test_isolation,
    validate_supervised_leakage_contract,
    validate_training_only_fit_scope,
)
from spy_market_agent.research.memory import ResearchMemoryRegistry
from spy_market_agent.research.metrics import (
    aggregate_metric,
    calculate_research_classification_metrics,
)
from spy_market_agent.research.migration import (
    RESEARCH_MIGRATION_RECEIPT_ID_VERSION,
    RESEARCH_MIGRATION_RECEIPT_SCHEMA_VERSION,
    ResearchMigrationReceipt,
    migrate_canonical_pair_to_research_memory,
    migrate_phase3_candidate_to_research_memory,
    research_migration_identity,
)
from spy_market_agent.research.phase3_adapters import (
    PHASE3_MIGRATION_TAG,
    phase3_candidate_to_axiom_result,
    phase3_manifest_to_axiom_experiment,
)
from spy_market_agent.research.protected import (
    assert_protected_evaluation_not_accessed,
    deny_protected_label_access,
)
from spy_market_agent.research.registries import (
    ablation_scaffold,
    baseline_feature_registry,
    baseline_model_registry,
    build_experiment_manifest,
    required_classification_baselines,
)
from spy_market_agent.research.reporting import (
    RESEARCH_REPORT_PREFIX,
    RESEARCH_REPORT_SCHEMA_VERSION,
    ResearchReportArtifact,
    render_research_report,
    report_artifact_path,
    research_report_name,
    write_research_report,
)
from spy_market_agent.research.resampling import (
    RESAMPLING_EVIDENCE_SCHEMA_VERSION,
    RESAMPLING_SOURCE_SCHEMA_VERSION,
    CanonicalResamplingEvidence,
    ResamplingConfig,
    ResamplingDistributionSummary,
    ResamplingMethod,
    canonical_resampling_evidence,
    resampling_evidence_to_axiom_result,
)
from spy_market_agent.research.robustness import (
    ROBUSTNESS_EVIDENCE_SCHEMA_VERSION,
    CanonicalRobustnessEvidence,
    MetricDirection,
    MetricRobustnessSummary,
    RobustnessScenario,
    RobustnessScenarioKind,
    canonical_robustness_evidence,
    robustness_evidence_to_axiom_result,
)
from spy_market_agent.research.runner import run_development_campaign
from spy_market_agent.research.scenario_candidate import (
    MI1D_CANDIDATE_ID,
    MI1D_FEATURE_COLUMNS,
    MI1D_FEATURE_POLICY_ID,
    MI1D_LOGISTIC_C,
    MI1D_LOGISTIC_MAX_ITER,
    MI1D_LOGISTIC_SOLVER,
    MI1D_LOGISTIC_TOL,
    MI1D_MINIMUM_FIT_ROWS,
    ScenarioCandidateBaselineComparison,
    ScenarioCandidateEvaluation,
    ScenarioCandidateFoldEvaluation,
    ScenarioCandidateModelSnapshot,
    evaluate_development_multinomial_candidate,
)
from spy_market_agent.research.scenario_evaluation import (
    MI1C_ASSESSMENT_WINDOW_ROWS,
    MI1C_MINIMUM_FINAL_ASSESSMENT_ROWS,
    MI1C_MINIMUM_INITIAL_FIT_ROWS,
    MI1C_POLICY_ID,
    MI1C_PROBABILITY_FLOOR,
    MI1C_STEP_ROWS,
    ScenarioBaselineBenchmark,
    ScenarioBaselineEvaluation,
    ScenarioBaselineFoldEvaluation,
    ScenarioEvaluationMetrics,
    calculate_scenario_probability_metrics,
    evaluate_development_naive_scenario_baselines,
)
from spy_market_agent.research.scenario_labels import (
    MI1B_5_SESSION_RANGE_BAND,
    MI1B_20_SESSION_RANGE_BAND,
    ScenarioBaseline,
    ScenarioBaselineKind,
    ScenarioLabel,
    ScenarioLabelSet,
    build_spy_scenario_label_set,
    classify_scenario_return,
    fit_naive_scenario_baseline,
)
from spy_market_agent.research.selection import (
    NO_CANDIDATE_PROMOTION,
    rank_classification_candidates,
)
from spy_market_agent.research.thresholds import (
    diagnostic_threshold_policy,
    strategy_threshold_policy,
)
from spy_market_agent.research.validation_contract import (
    VALIDATION_CASE_ID_VERSION,
    VALIDATION_CASE_SCHEMA_VERSION,
    VALIDATION_REQUIRED_EVIDENCE_STAGES,
    ValidationCase,
    ValidationEvidenceRef,
    ValidationEvidenceSourceKind,
    ValidationStage,
    build_validation_case,
    validation_case_identity,
)
from spy_market_agent.research.validation_engine import (
    VALIDATION_DECISION_SCHEMA_VERSION,
    MetricThreshold,
    ResamplingThreshold,
    RobustnessThreshold,
    ValidationDecision,
    ValidationGateResult,
    ValidationGateStatus,
    ValidationPolicy,
    ValidationVerdict,
    evaluate_validation_case,
)

__all__ = [
    "AXIOM_EXPERIMENT_ID_VERSION",
    "AXIOM_EXPERIMENT_SCHEMA_VERSION",
    "AXIOM_RESULT_ID_VERSION",
    "AXIOM_RESULT_SCHEMA_VERSION",
    "BACKTEST_EVIDENCE_SCHEMA_VERSION",
    "BOUNDARY_EXCLUSION_SESSIONS",
    "DEFAULT_ASSESSMENT_WINDOW_ROWS",
    "DEFAULT_STEP_ROWS",
    "ENTRY_OFFSET_SESSIONS",
    "EXIT_OFFSET_SESSIONS",
    "FEATURE_WARMUP_ROWS",
    "MANDATORY_GAP_SESSIONS",
    "MI1B_5_SESSION_RANGE_BAND",
    "MI1B_20_SESSION_RANGE_BAND",
    "MI1C_ASSESSMENT_WINDOW_ROWS",
    "MI1C_MINIMUM_FINAL_ASSESSMENT_ROWS",
    "MI1C_MINIMUM_INITIAL_FIT_ROWS",
    "MI1C_POLICY_ID",
    "MI1C_PROBABILITY_FLOOR",
    "MI1C_STEP_ROWS",
    "MI1D_CANDIDATE_ID",
    "MI1D_FEATURE_COLUMNS",
    "MI1D_FEATURE_POLICY_ID",
    "MI1D_LOGISTIC_C",
    "MI1D_LOGISTIC_MAX_ITER",
    "MI1D_LOGISTIC_SOLVER",
    "MI1D_LOGISTIC_TOL",
    "MI1D_MINIMUM_FIT_ROWS",
    "MINIMUM_FINAL_ASSESSMENT_ROWS",
    "MINIMUM_INITIAL_TRAINING_ROWS",
    "NO_CANDIDATE_PROMOTION",
    "PHASE3_ARTIFACT_SCHEMA_VERSION",
    "PHASE3_MIGRATION_TAG",
    "PHASE3_PHASE_ID",
    "RESAMPLING_EVIDENCE_SCHEMA_VERSION",
    "RESAMPLING_SOURCE_SCHEMA_VERSION",
    "RESEARCH_MIGRATION_RECEIPT_ID_VERSION",
    "RESEARCH_MIGRATION_RECEIPT_SCHEMA_VERSION",
    "RESEARCH_REPORT_PREFIX",
    "RESEARCH_REPORT_SCHEMA_VERSION",
    "ROBUSTNESS_EVIDENCE_SCHEMA_VERSION",
    "VALIDATION_CASE_ID_VERSION",
    "VALIDATION_CASE_SCHEMA_VERSION",
    "VALIDATION_DECISION_SCHEMA_VERSION",
    "VALIDATION_REQUIRED_EVIDENCE_STAGES",
    "WALK_FORWARD_FOLD_POLICY_ID",
    "CanonicalBacktestEvidence",
    "CanonicalResamplingEvidence",
    "CanonicalRobustnessEvidence",
    "ExperimentDefinition",
    "ExperimentLifecycleState",
    "ExperimentOutcome",
    "ExperimentResult",
    "FeatureGenerationPolicy",
    "MetricDirection",
    "MetricRobustnessSummary",
    "MetricThreshold",
    "ResamplingConfig",
    "ResamplingDistributionSummary",
    "ResamplingMethod",
    "ResamplingThreshold",
    "ResearchArtifactStore",
    "ResearchCampaignConfig",
    "ResearchDatasetRef",
    "ResearchEvidenceRef",
    "ResearchMemoryRegistry",
    "ResearchMigrationReceipt",
    "ResearchReportArtifact",
    "ResearchRuntimeLineage",
    "RobustnessScenario",
    "RobustnessScenarioKind",
    "RobustnessThreshold",
    "ScenarioBaseline",
    "ScenarioBaselineBenchmark",
    "ScenarioBaselineEvaluation",
    "ScenarioBaselineFoldEvaluation",
    "ScenarioBaselineKind",
    "ScenarioCandidateBaselineComparison",
    "ScenarioCandidateEvaluation",
    "ScenarioCandidateFoldEvaluation",
    "ScenarioCandidateModelSnapshot",
    "ScenarioEvaluationMetrics",
    "ScenarioLabel",
    "ScenarioLabelSet",
    "StoredExperiment",
    "StoredExperimentResult",
    "StrategyResearchState",
    "TransformationFitRecord",
    "ValidationCase",
    "ValidationDecision",
    "ValidationEvidenceRef",
    "ValidationEvidenceSourceKind",
    "ValidationGateResult",
    "ValidationGateStatus",
    "ValidationPolicy",
    "ValidationStage",
    "ValidationVerdict",
    "ablation_scaffold",
    "aggregate_metric",
    "assert_protected_evaluation_not_accessed",
    "axiom_experiment_identity",
    "axiom_result_identity",
    "backtest_metrics_to_axiom_result",
    "baseline_feature_registry",
    "baseline_model_registry",
    "build_calibration_split",
    "build_experiment_manifest",
    "build_spy_scenario_label_set",
    "build_validation_case",
    "calculate_research_classification_metrics",
    "calculate_scenario_probability_metrics",
    "campaign_config_identity",
    "canonical_backtest_evidence",
    "canonical_resampling_evidence",
    "canonical_robustness_evidence",
    "classification_baseline_probabilities",
    "classify_scenario_return",
    "construct_walk_forward_manifest",
    "deny_protected_label_access",
    "development_hyperparameter_searches",
    "development_model_registry",
    "diagnostic_threshold_policy",
    "evaluate_development_multinomial_candidate",
    "evaluate_development_naive_scenario_baselines",
    "evaluate_validation_case",
    "experiment_identity",
    "fit_naive_scenario_baseline",
    "fold_manifest_identity",
    "load_research_campaign_config",
    "migrate_canonical_pair_to_research_memory",
    "migrate_phase3_candidate_to_research_memory",
    "phase3_candidate_to_axiom_result",
    "phase3_manifest_to_axiom_experiment",
    "planned_trials_from_grid",
    "rank_classification_candidates",
    "render_research_report",
    "report_artifact_path",
    "required_classification_baselines",
    "resampling_evidence_to_axiom_result",
    "research_migration_identity",
    "research_report_name",
    "robustness_evidence_to_axiom_result",
    "run_development_campaign",
    "strategy_threshold_policy",
    "validate_inner_training_search",
    "validate_no_forbidden_feature_columns",
    "validate_phase2_final_test_isolation",
    "validate_supervised_leakage_contract",
    "validate_training_only_fit_scope",
    "validation_case_identity",
    "write_research_report",
]
